name: 'Setup Fish Shell'
description: 'Install Fish shell with caching support'
inputs:
  fish-version:
    description: 'Fish version to install (default: latest)'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Cache Fish installation
      id: cache-fish
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/bin/fish
          ~/.config/fish
          /usr/local/bin/fish
          /opt/homebrew/bin/fish
        key: ${{ runner.os }}-fish-${{ inputs.fish-version }}-${{ hashFiles('.github/actions/setup-fish/action.yml') }}

    - name: Install Fish (Ubuntu)
      if: runner.os == 'Linux' && steps.cache-fish.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository -y ppa:fish-shell/nightly-master
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends fish

    - name: Install Fish (macOS)
      if: runner.os == 'macOS' && steps.cache-fish.outputs.cache-hit != 'true'
      shell: bash
      run: brew install fish

    - name: Verify Fish installation
      shell: bash
      run: fish --version